### ISSUE TITLE
Spellbook Swap included by default please

### ISSUE THREAD

**Issue by Puzzle-Drops** [Mantic-says-hi/arceuus-timers#11]
![image](https://github.com/Mantic-says-hi/arceuus-timers/assets/86485071/438db3db-5c2a-41cc-9ea2-3739f7580cfe)

Please add SBS to the timers list.

**Comment by Mantic-says-hi** [comment]
I will work on putting this in.

**Comment by Mantic-says-hi** [comment]
Commit : https://github.com/Mantic-says-hi/arceuus-timers/commit/d4666f3db0dc47689673587f4cb39c4c5c16d2f4

Changes made and pull request for plugin hub started.
