### ISSUE TITLE
Mark of Darkness

### ISSUE THREAD

**Issue by EnuDelrum** [Mantic-says-hi/arceuus-timers#9]
Now that Mark of Darkness is a player buff, can this plugin be updated to give a countdown timer after Mark of Darkness has been cast until it wears off? (0.6 seconds * current magic level)

**Comment by Mantic-says-hi** [comment]
I will start implementing this now, thank you for bringing this up as I missed this in the patch notes recently.

**Comment by Mantic-says-hi** [comment]
Update 1.4 sent off to plugin hub pull request, sorry for the delay in getting this done.
